"""added role to user table

Revision ID: 834ab4806ae8
Revises: 116aa1a88182
Create Date: 2023-05-13 23:01:01.417710

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '834ab4806ae8'
down_revision = '116aa1a88182'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('docpad_users', sa.Column('role', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('docpad_users', 'role')
    # ### end Alembic commands ###
